WIP - Add vetting to test script and fix the first few things that it found
We need to get vetting to pass across the board. There are probably a hundred+ problems that still need fixing.

diff --git a/test b/test
--- a/test
+++ b/test
@@ -10,6 +10,20 @@ set_death_dir $START_DIR
 
 say "BEGIN"
 
+# Lint all source files first
+PASS=1
+for f in `find . -name "*.go"`; do
+	go vet $f
+	if [ $? != 0 ]; then
+		PASS=0
+	fi
+done
+if [ $PASS == 0 ]; then
+	die "FAILED Vetting stage!"
+fi
+
+
+# Now run unit tests
 for testrunner in `find $SCRIPT_DIR -name "t"`; do
 	echo "Running test: '$testrunner'"
 	/bin/bash $testrunner
