WIP - Improve build/test scripts to self-recover from missing package dependencies

diff --git a/test b/test
--- a/test
+++ b/test
@@ -12,11 +12,34 @@ say "BEGIN"
 
 # Lint all source files first
 PASS=1
-#for f in `find . -name "*.go"`; do
+gobin=`which go`
 for f in `find . -type f -name '*.go' | sed -r 's|/[^/]+$||' |sort |uniq`; do
-	go vet $f
+	# Try to vet this file
+	output=`go vet $f 2>&1`
 	if [ $? != 0 ]; then
+		# Mark as failed if there was a non-zero return
 		PASS=0
+	fi
+	# If there was any verbose output...
+	if [ "" != "$output" ]; then
+		# Echo the output
+		echo "Vet error: $output"
+		# But also check if it's complaining that we need to go get some package dependency
+		cmd=`echo $output | grep "go get" | sed -e 's/.* go get //g'`
+		if [ "" != "$cmd" ]; then
+			# If so, then go get it...
+			echo "cmd: $gobin get $cmd"
+			`$gobin get $cmd`
+			# And then try vet again
+			output=`go vet $f 2>&1`
+			if [ $? == 0 ]; then
+				# If it worked this time, then all good!
+				PASS=1
+			else
+				# Still failed. stop.
+				break
+			fi
+		fi
 	fi
 done
 if [ $PASS == 0 ]; then
