Add Testing Expect funcs for non|empty strings

diff --git a/test b/test
--- a/test
+++ b/test
@@ -20,16 +20,23 @@ for f in `find . -type f -name '*.go' | sed -r 's|/[^/]+$||' |sort |uniq`; do
 	fi
 done
 if [ $PASS == 0 ]; then
-	die "FAILED Vetting stage!"
+	die "FAILED Vetting stage (see above)!"
 fi
 
 
 # Now run unit tests
+PASS=1
 for testrunner in `find $SCRIPT_DIR -name "t"`; do
 	echo "Running test: '$testrunner'"
 	/bin/bash $testrunner
+	if [ $? != 0 ]; then
+		PASS=0
+	fi
 done
 
 cd $START_DIR
+if [ $PASS == 0 ]; then
+	die "FAILED Testing stage (see above)!"
+fi
 say "\nDONE! :^D"
 
